### ISSUE TITLE
Prepare test suite

### ISSUE THREAD

**Issue by DavidKang** [team-of-davids/yet-another-personal-diary#11]
We have to define what gems use to do test, we can use some of them:

- [Rspec](https://github.com/rspec/rspec-rails)

- [Mini Test](https://github.com/blowmage/minitest-rails)

- [Shoulda Matchers](https://github.com/thoughtbot/shoulda-matchers)

- [FactoryGirl](https://github.com/thoughtbot/factory_girl_rails)

- [Database Cleaner](https://github.com/DatabaseCleaner/database_cleaner)

...

@dgdavid what you prefer, Rspec or MiniTest?

**Comment by dgdavid** [comment]
I prefer to use `RSpec` :)

**Comment by DavidKang** [comment]
nice :)
